### ISSUE TITLE
Crash with aligned sorting and compute spike amplitudes

### ISSUE THREAD

**Issue by DradeAW** [SpikeInterface/spikeinterface#1075]
Hi,

There is a bug when using `compute_spike_amplitudes` on an aligned sorting.
If a spike is not inside the recording window after alignment, it will cause a crash.

Here are the steps to reproduce:

```python
import numpy as np
import spikeinterface.core as si
from spikeinterface.core.testing_tools import generate_recording
import spikeinterface.postprocessing as spost

sf = 30000
recording = generate_recording(sampling_frequency=sf, durations=[8.])
sorting = si.NumpySorting.from_dict({0: np.array([100, 2000, 5000]), 1: np.array([2, 3500, 3502, 8000])}, 30000)

wvf_extractor = si.extract_waveforms(recording, sorting, mode="memory", allow_unfiltered=True)
spost.compute_spike_amplitudes(wvf_extractor, outputs="by_unit")  # Works as intended.
> [{0: array([-0.45386556, -0.95153034, -1.2255398 ], dtype=float32), 1: array([-0.00670461, -3.3331778 , -3.1237051 ,  0.5309616 ], dtype=float32)}]

sorting_aligned = spost.align_sorting(sorting, {0: 4, 1: 3})  # The first spike of unit '1' now is before the recording starts.
wvf_extractor = si.extract_waveforms(recording, sorting_aligned, mode="memory", allow_unfiltered=True)
spost.compute_spike_amplitudes(wvf_extractor, outputs="by_unit")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/postprocessing/spike_amplitudes.py", line 176, in compute_spike_amplitudes
    amps = sac.get_data(outputs=outputs)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/postprocessing/spike_amplitudes.py", line 119, in get_data
    amps = self._extension_data[f'amplitude_segment_{segment_index}'][mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 7
```

**Comment by alejoe91** [comment]
I think this is fixed with #1378

Excess spikes must now be removed before extracting waveforms (the second time)
