### ISSUE TITLE
TypeError: Object of type ndarray is not JSON serializable

### ISSUE THREAD

**Issue by tduvan** [SpikeInterface/spikeinterface#1144]
Hi,

I'm trying to build a spike sorting pipeline for data recorded with the Openephys Kwik format. I've  managed to load the data as a numb array but I think this is creating some problems.

* Initially I tried doing spike sorting using dockers but I started receiving the TypeError, then I moved to using locally installed ironclust and the problem still continued. While looking at the previously reported issues I've found out that ndarray type needs to be saved in order to be able to continue processing however when I try to save my extractor object I'm still getting "Object of type ndarray is not JSON serializable" error.

I'm sharing my code and the full error log below. Would you be able to help me?

    recording = se.NumpyRecording(traces_list=segmented_traces, sampling_frequency=sampling_frequency,
    channel_ids=list(range(num_channels)))

    probe = gp(num_elec=num_channels, ypitch=20, contact_shapes='circle', contact_shape_params={'radius': 12.5})
    probe.set_device_channel_indices([x - 1 for x in electrode_channels])
    recording = recording.set_probe(probe)

    plt.ion()
    sw.plot_timeseries(recording, segment_index=1, channel_ids=[1])

    centered_recording = preprocess.center(recording)
    filtered_recording = preprocess.filter(centered_recording, band=[300.0, 6000.0], btype='bandpass', filter_order=2,
                                           ftype='butter', filter_mode='ba', margin_ms=5.0)

    # run spike sorting on entire recording
    concatenated_recording = si.concatenate_recordings([filtered_recording])

    saved_recording = concatenated_recording.save(folder='preprocessed', progress_bar=True)

    ss.IronClustSorter.set_ironclust_path('./ironclust')
    sorting_KS2 = ss.run_sorter('ironclust', rec2,
                                output_folder='results_KS2', verbose=True)

    sw.plot_timeseries(filtered_recording, segment_index=1)
    # sw.plot_rasters(sorting_true, time_range=(0, 5))

-------------------------------------------------------------------------------

    /Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/site-packages/spikeinterface/core/core_tools.py:112: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
      v_arr = np.array(v)
    Traceback (most recent call last):
      File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
        pydev_imports.execfile(file, globals, locals)  # execute the script
      File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "/Users/taygunduvan/Library/CloudStorage/OneDrive-INSTITUTCATALÀDENANOCIENCIAINANOTECNOLOGÍA/PyCharm/spikeInterfaceProject/main.py", line 82, in <module>
        saved_recording = concatenated_recording.save(folder='preprocessed', progress_bar=True)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/site-packages/spikeinterface/core/base.py", line 622, in save
        loaded_extractor = self.save_to_folder(**kwargs)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/site-packages/spikeinterface/core/base.py", line 691, in save_to_folder
        self.dump(provenance_file)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/site-packages/spikeinterface/core/base.py", line 464, in dump
        self.dump_to_json(file_path, relative_to=relative_to, folder_metadata=folder_metadata)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/site-packages/spikeinterface/core/base.py", line 490, in dump_to_json
        json.dumps(check_json(dump_dict), indent=4),
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/__init__.py", line 238, in dumps
        **kw).encode(obj)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 201, in encode
        chunks = list(chunks)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 431, in _iterencode
        yield from _iterencode_dict(o, _current_indent_level)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
        yield from chunks
      [Previous line repeated 3 more times]
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
        yield from chunks
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 438, in _iterencode
        o = _default(o)
      File "/Users/taygunduvan/.conda/envs/spikeInterfaceEnv/lib/python3.10/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type ndarray is not JSON serializable

**Comment by tduvan** [comment]
Hi @alejoe91

Thank you very much for your response, it worked like a charm :).
