### ISSUE TITLE
run_sorter expects the same # of channels after splitting sorter by groups in new API

### ISSUE THREAD

**Issue by timsainb** [SpikeInterface/spikeinterface#140]
My guess is that this is because the probe file with 32 channels is kept constant. It seems to me like the default behavior here should be to split the probe file in the recording into sub-probes, or something like that. 

```python
# recording is a buzsaki32
sub_recordings = recording.split_by(property='group', outputs='list')

> sub_recordings
[ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz,
 ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz,
 ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz,
 ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz]

for sub_recording in tqdm(sub_recordings):
    with tempfile.TemporaryDirectory(dir=tmp_loc) as tmpdir:
        print(tmpdir)
        sort = ss.run_sorter(
            sorter_name='tridesclous',
            recording=sub_recording,
            output_folder=Path(tmpdir),
            verbose=True,
        )
> ValueError: could not broadcast input array from shape (651041,32) into shape (651041,8)
```

This isn't critical for me, I just wanted to point it out.

**Comment by timsainb** [comment]
On second glance, it looks like the probe is splitting

```python
sub_recordings[0].get_probe()
> ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz
```

I'm looking into why the sorter still thinks there's 32 channels now.

**Comment by timsainb** [comment]
Here's the full output:
```python
"""
Traceback (most recent call last):
  File "/mnt/cube/tsainbur/conda_envs/cdcp_env_shared/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/mnt/cube/tsainbur/conda_envs/cdcp_env_shared/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/mnt/cube/tsainbur/conda_envs/cdcp_env_shared/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/mnt/cube/tsainbur/Projects/github_repos/spikeinterface/spikeinterface/core/job_tools.py", line 225, in function_wrapper
    return _func(segment_index, start_frame, end_frame, _worker_ctx)
  File "/mnt/cube/tsainbur/Projects/github_repos/spikeinterface/spikeinterface/core/core_tools.py", line 126, in _write_binary_chunk
    rec_memmap[start_frame:end_frame, :] = traces
ValueError: could not broadcast input array from shape (651041,32) into shape (651041,8)
"""
```
It looks like _write_binary_chunk  is grabbing all 32 channels  of traces for some reason.

**Comment by alejoe91** [comment]
If you `get_traces ` from the sub recording is the shape correct?

**Comment by samuelgarcia** [comment]
Strange.
I did  made quick test and it was woring.
The example is broken so I need to fix it.
https://spikeinterface.readthedocs.io/en/latest/modules/sorters/plot_3_sorting_by_group.html#sphx-glr-modules-sorters-plot-3-sorting-by-group-py

Maybe it is related to a partiicular neo.io/extractor which have bug when slicing on the fly.
What is the extractor in your example. Do you reproduce this with evry extractor ?

**Comment by timsainb** [comment]
@alejoe91 
```python
sub_recordings[0]
> ChannelSliceRecording: 8 channels - 1 segments - 30.0kHz

sub_recordings[0].get_num_channels()
> 8
traces = sub_recordings[0].get_traces(start_frame=0, end_frame=1000)
traces.shape
> (300000, 32)
```

**Comment by timsainb** [comment]
False alarm, my bad guys. It was an issue with a custom preprocessor I wrote. Thanks for helping me find the issue.
