### ISSUE TITLE
Problem running Mountainsort4

### ISSUE THREAD

**Issue by szbalazs98** [SpikeInterface/spikeinterface#171]
Hi,
I tried to run Mountainsort4 on the data that was given in the Cambridge webinar like this:
sorting_MS = ss.run_mountainsort4(recording_cache, grouping_property='group', adjacency_radius=50, parallel=True, 
                                                          verbose=True, output_folder='results_mountainsort4', filter=False)

It gave this error:
"""
Traceback (most recent call last):
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\spikesorters\mountainsort4\mountainsort4.py", line 107, in _run
    sorting = ml_ms4alg.mountainsort4(
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\site-packages\ml_ms4alg\mountainsort4.py", line 29, in mountainsort4
    tmpdir = tempfile.mkdtemp(dir=os.environ.get('TEMPDIR','/tmp'))
  File "C:\Users\Bazsi\anaconda3\envs\spiketutorial\lib\tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [WinError 3] The system cannot find the specified path: '/tmp\\tmptycoc_6j' (or something like this, because my computer's language is hungarian so I translated it)

An other thing that concerns me is that after I install Mountainsort4 it gives warning about deprications because of numpy. Could it be the source of the problem. I can try downgrading numpy, but in my experience it is not a good idea.

Thanks in advance for your help!

**Comment by samuelgarcia** [comment]
Now montainsort need the python pacakge `mountainsort4` and not anymore the `ml_ms4alg` package.

This is implemented in the "new API" which is not yet released.
The tutorial you mention is based on 0.12 version.
If you go for the futur version ("new api") from source , you certainly need to adapt your code, check [new api tutorials](https://spikeinterface.readthedocs.io/en/latest/modules/index.html) for this.

You can also solve your problem with this https://github.com/SpikeInterface/spikesorters/pull/215 using the old spikeinterface api.
