### ISSUE TITLE
preprocessing filter stage not evaluating Wn?

### ISSUE THREAD

**Issue by avakiai** [SpikeInterface/spikeinterface#1713]
Hi, 

I'm trying to run a spykingcircus 2 sorter on some data after pre-processing. I'm running into an error that seems to occur in the preprocessing/filter.py module. 

Running the following:
```
import os
import numpy as np
import matplotlib.pyplot as plt
from pprint import pprint
import spikeinterface as si  # import core only
import spikeinterface.extractors
import spikeinterface.extractors as se
import spikeinterface.preprocessing as spre
import spikeinterface.sorters as ss
import spikeinterface.postprocessing as spost
import spikeinterface.qualitymetrics as sqm
import spikeinterface.comparison as sc
import spikeinterface.exporters as sexp
import spikeinterface.curation as scur
import spikeinterface.widgets as sw
from probeinterface import generate_linear_probe, io
from probeinterface.plotting import plot_probe

# [load in/assign directories]
recording = se.read_mcsh5(files[0])

# preprocessing
# 1. high-pass filter
recording_f = spre.bandpass_filter(recording, freq_min=300, freq_max=3000)
# 2. common reference (remove median)
recording_cmr = spre.common_reference(recording_f, operator="median")
# 3. whiten 
recording_w = spre.whiten(recording_cmr)

# sorting
sorting = ss.run_sorter('spykingcircus2', recording_w, output_folder='./sc2', verbose=True)

```
Gives this error:
```
Error running spykingcircus2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\sorters\basesorter.py", line 226, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\sorters\internal\spyking_circus2.py", line 67, in _run_from_folder
    recording_f = bandpass_filter(recording, **filtering_params)
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\core\core_tools.py", line 26, in reader_func
    return source_class(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\preprocessing\filter.py", line 159, in __init__
    FilterRecording.__init__(self, recording, band=[freq_min, freq_max], margin_ms=margin_ms, dtype=dtype,
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\preprocessing\filter.py", line 76, in __init__
    filter_coeff = scipy.signal.iirfilter(N, Wn, analog=False, btype=btype, ftype=ftype, output=filter_mode)
  File "C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\scipy\signal\_filter_design.py", line 2556, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Cell In[69], line 2
      1 # sorting
----> 2 sorting = ss.run_sorter('spykingcircus2', recording_w, output_folder='./sc2', verbose=True)

File C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\sorters\runsorter.py:143, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, with_output, **sorter_params)
    136             container_image = singularity_image
    137     return run_sorter_container(
    138         container_image=container_image,
    139         mode=mode,
    140         **common_kwargs,
    141     )
--> 143 return run_sorter_local(**common_kwargs)

File C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\sorters\runsorter.py:163, in run_sorter_local(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, **sorter_params)
    160 SorterClass.set_params_to_folder(
    161     recording, output_folder, sorter_params, verbose)
    162 SorterClass.setup_recording(recording, output_folder, verbose=verbose)
--> 163 SorterClass.run_from_folder(output_folder, raise_error, verbose)
    164 if with_output:
    165     sorting = SorterClass.get_result_from_folder(output_folder)

File C:\ProgramData\Anaconda3\envs\spikeinterface\lib\site-packages\spikeinterface\sorters\basesorter.py:262, in BaseSorter.run_from_folder(cls, output_folder, raise_error, verbose)
    260 if has_error and raise_error:
    261     print(log['error_trace'])
--> 262     raise SpikeSortingError(
    263         f"Spike sorting failed. You can inspect the runtime trace in {output_folder}/spikeinterface_log.json")
    265 return run_time

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in sc2/spikeinterface_log.json

```

The issue seems to be that the scipy filter used under the hood wants the frequency band in 0:1. But this should be calculated already in the preprocessing/filter/py file at:
```
        if coeff is None:
            assert btype in ('bandpass', 'highpass')
            # coefficient
            if btype in ('bandpass', 'bandstop'):
                assert len(band) == 2
                Wn = [e / sf * 2 for e in band]
            else:
                Wn = float(band) / sf * 2
            N = filter_order
            # self.coeff is 'sos' or 'ab' style
            filter_coeff = scipy.signal.iirfilter(N, Wn, analog=False, btype=btype, ftype=ftype, output=filter_mode)
```
So I don't see why it's throwing this error. 

Giving the frequency cutoffs as f/Fs doesn't work of course, but leaving them as default values doesn't either. Additionally, I get the same error whether I omit the preprocessing altogether or not. One thought was that somewhere the sampling rate is not being read properly. However recording.get_sampling_frequency() looks normal. 

How to solve?

**Comment by yger** [comment]
What is your sampling_rate? Because you should have freq_max < 0.95*sampling_rate / 2

**Comment by alejoe91** [comment]
@avakiai can you paste here the output of `print(recording)`?

**Comment by avakiai** [comment]
Hi, here's the output of `print(recording)`

```
MCSH5RecordingExtractor: 16 channels - 1 segments - 10.0kHz - 42.900s
  file_path: D:\...\M1_anesth_post_natsyll_n01.h5
```
Though I run the sorter on some preprocessed recording objects:
```
WhitenRecording: 16 channels - 1 segments - 10.0kHz - 42.900s
```

**Comment by alejoe91** [comment]
I see! The problem is that SC2 attempts to filter the recording by default, with default cutoffs of 300-6000 Hz. You should use the `apply_preprocessing=False` parameter, since you're preprocessing outside:
```
sorting = ss.run_sorter('spykingcircus2', recording_w, output_folder='./sc2', verbose=True, apply_preprocessing=False)
```

**Comment by avakiai** [comment]
Hi! Aha. So it does seem to run now, but I do in fact want preprocessing, namely between 300 and 3000 Hz, as per: 
```
# preprocessing
# 1. high-pass filter
recording_f = spre.bandpass_filter(recording, freq_min=300, freq_max=3000)
```
As my Fs is 10kHz, the max freq is 5kHz. If i add the apply_preprocessing=False flag, then I presume it wouldn't bandpass filter my data.

**Comment by avakiai** [comment]
Ok thanks! Just to be sure I understand though: I though the preprocessing functions are lazy in that they dont apply the transformations, but the transforms are applied at the point of run_sorter(). Is that not the case? So, providing recording_w is passing filtered, referenced, and whitened data?

**Comment by alejoe91** [comment]
Exactly, and the sorter will use the processed traces when needed

**Comment by avakiai** [comment]
Great, thanks!
