### ISSUE TITLE
`recording.has_channel_location()` doesn't work like it's supposed to

### ISSUE THREAD

**Issue by DradeAW** [SpikeInterface/spikeinterface#1805]
Hi,

I'm having a crash while trying to run Lussac's unit tests:

The code that makes it crash:
```python
print("lol1")
print(recording.get_probegroup())
print(recording.get_property_keys())
print(recording.has_channel_location())

sorting = ss.run_sorter("spykingcircus2", recording, **params['sorter_params'])
```

I also modified `waveform_extractor.extract_waveform` to add a print in the beginning:
```python
print("lol2")
print(recording.get_probegroup())
print(recording.get_property_keys())
print(recording.has_channel_location())
assert (
    recording.has_channel_location()
), "Recording must have a probe  or channel location to extract waveforms. Use the `set_probe()` or `set_dummy_probe_from_locations()` methods."
```

And here is the output of pytest:
```bash
$ pytest tests/core/test_spike_sorting.py
============================================================== test session starts ==============================================================
platform linux -- Python 3.11.2, pytest-7.4.0, pluggy-1.0.0
cachedir: tests/.pytest_cache
rootdir: /export/home1/users/nsr/wyngaard/Documents/lussac2
configfile: pyproject.toml
plugins: cov-4.1.0
collected 1 item                                                                                                                                

tests/core/test_spike_sorting.py F                                                                                                        [100%]

=================================================================== FAILURES ====================================================================
______________________________________________________________ test_spike_sorting _______________________________________________________________

data = <lussac.core.lussac_data.LussacData object at 0x7fb8c8f001c0>

    @pytest.mark.skipif(importlib.util.find_spec("hdbscan") is None, reason="Testing spike sorting requires Python package 'hdbscan'.")
    def test_spike_sorting(data: LussacData) -> None:
    	"""
    	Tests if spike sorting can be run through Lussac without any crash.
    	Creates a shorter recording (1 shank, 5 minutes) to go faster.
    	We don't really care about quality here (e.g. no preprocessing)
    	because we only want to check that the spike sorting can be run.
    	"""
    	start_frame, end_frame = 9_000_000, 18_000_000
    	name = "test_spike_sorting"
    
    	recording = data.recording.frame_slice(start_frame, end_frame)
    	recording = recording.channel_slice(np.arange(13, 26))
    	params = {
    		'sorter_name': "spykingcircus2",
    		'preprocessing': {
    			'filter': {'band': [150., 6000.], 'filter_order': 2, 'ftype': "bessel"},
    			'common_reference': {'operator': "median"}
    		},
    		'sorter_params': {
    			'detection': {'peak_sign': "neg", "detect_threshold": 7},
    			'apply_preprocessing': False,
    			'output_folder': f"{data.tmp_folder}/sc2_ss_test"
    		}
    	}
    
    	spike_sorter = LussacSpikeSorter(recording, name)
>   	sorting = spike_sorter.launch(params)

tests/core/test_spike_sorting.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/lussac/core/spike_sorting.py:63: in launch
    sorting = ss.run_sorter(sorter_name, self.recording, **params['sorter_params'])
../../dev/spikeinterface/spikeinterface/src/spikeinterface/sorters/runsorter.py:148: in run_sorter
    return run_sorter_local(**common_kwargs)
../../dev/spikeinterface/spikeinterface/src/spikeinterface/sorters/runsorter.py:174: in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'spikeinterface.sorters.internal.spyking_circus2.Spykingcircus2Sorter'>
output_folder = PosixPath('/export/home1/users/nsr/wyngaard/Documents/lussac2/tests/datasets/cerebellar_cortex/tmp_cwf7w9es/sc2_ss_test')
raise_error = True, verbose = False

    @classmethod
    def run_from_folder(cls, output_folder, raise_error, verbose):
        # need setup_recording to be done.
        output_folder = Path(output_folder)
        sorter_output_folder = output_folder / "sorter_output"
    
        # retrieve sorter_name and params
        with (output_folder / "spikeinterface_params.json").open(mode="r") as f:
            params = json.load(f)
        sorter_params = params["sorter_params"]
        sorter_name = params["sorter_name"]
    
        from .sorterlist import sorter_dict
    
        SorterClass = sorter_dict[sorter_name]
    
        now = datetime.datetime.now()
        log = {
            "sorter_name": str(SorterClass.sorter_name),
            "sorter_version": str(SorterClass.get_sorter_version()),
            "datetime": now,
            "runtime_trace": [],
        }
        t0 = time.perf_counter()
    
        try:
            SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
            t1 = time.perf_counter()
            run_time = float(t1 - t0)
            has_error = False
        except Exception as err:
            has_error = True
            run_time = None
            log["error"] = True
            log["error_trace"] = traceback.format_exc()
    
        log["error"] = has_error
        log["run_time"] = run_time
    
        # some sorter have a log file dur to shellscript launcher
        runtime_trace_path = sorter_output_folder / f"{sorter_name}.log"
        runtime_trace = []
        if runtime_trace_path.is_file():
            with open(runtime_trace_path, "r") as fp:
                line = fp.readline()
                while line:
                    runtime_trace.append(line.strip())
                    line = fp.readline()
        log["runtime_trace"] = runtime_trace
    
        # dump to json
        with (output_folder / "spikeinterface_log.json").open("w", encoding="utf8") as f:
            json.dump(check_json(log), f, indent=4)
    
        if verbose:
            if has_error:
                print(f"Error running {sorter_name}")
            else:
                print(f"{sorter_name} run time {run_time:0.2f}s")
    
        if has_error and raise_error:
>           raise SpikeSortingError(
                f"Spike sorting error trace:\n{log['error_trace']}\n"
                f"Spike sorting failed. You can inspect the runtime trace in {output_folder}/spikeinterface_log.json."
            )
E           spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting error trace:
E           Traceback (most recent call last):
E             File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sorters/basesorter.py", line 234, in run_from_folder
E               SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
E             File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sorters/internal/spyking_circus2.py", line 112, in _run_from_folder
E               labels, peak_labels = find_cluster_from_peaks(
E                                     ^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sortingcomponents/clustering/main.py", line 41, in find_cluster_from_peaks
E               labels, peak_labels = method_class.main_function(recording, peaks, params)
E                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E             File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sortingcomponents/clustering/random_projections.py", line 214, in main_function
E               we = extract_waveforms(
E                    ^^^^^^^^^^^^^^^^^^
E             File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/core/waveform_extractor.py", line 1538, in extract_waveforms
E               assert (
E           AssertionError: Recording must have a probe  or channel location to extract waveforms. Use the `set_probe()` or `set_dummy_probe_from_locations()` methods.
E           
E           Spike sorting failed. You can inspect the runtime trace in /export/home1/users/nsr/wyngaard/Documents/lussac2/tests/datasets/cerebellar_cortex/tmp_cwf7w9es/sc2_ss_test/spikeinterface_log.json.

../../dev/spikeinterface/spikeinterface/src/spikeinterface/sorters/basesorter.py:269: SpikeSortingError
------------------------------------------------------------- Captured stdout call --------------------------------------------------------------
lol1
<probeinterface.probegroup.ProbeGroup object at 0x7fb8c66f8890>
['gain_to_uV', 'offset_to_uV', 'contact_vector', 'location', 'group']
True
lol2
<probeinterface.probegroup.ProbeGroup object at 0x7fb8c49155d0>
['gain_to_uV', 'offset_to_uV', 'group', 'location', 'noise_level_raw']
False
=============================================================== warnings summary ================================================================
tests/core/test_spike_sorting.py::test_spike_sorting
  /export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sortingcomponents/peak_detection.py:643: NumbaDeprecationWarning:
  
  The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

tests/core/test_spike_sorting.py::test_spike_sorting
  /export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sortingcomponents/peak_detection.py:668: NumbaDeprecationWarning:
  
  The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

tests/core/test_spike_sorting.py::test_spike_sorting
  /export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/sortingcomponents/clustering/sliding_nn.py:370: NumbaDeprecationWarning:
  
  The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

tests/core/test_spike_sorting.py::test_spike_sorting
  /export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/src/spikeinterface/core/baserecordingsnippets.py:228: UserWarning:recording.has_channel_location()
  
  There is no Probe attached to this recording. Creating a dummy one with contact positions

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================ short test summary info ============================================================
FAILED tests/core/test_spike_sorting.py::test_spike_sorting - spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting error trace:
======================================================== 1 failed, 4 warnings in 18.22s =========================================================
```

As you can see, `recording.has_channel_location()` returns False once the `recording` object has been pre-processessed, but that shouldn't happen.

**Comment by DradeAW** [comment]
I think that the error comes from here:
https://github.com/SpikeInterface/spikeinterface/blob/802743208e9240e9b86888ff2da7473e7a64c302/src/spikeinterface/core/base.py#L574

The `recording` object is dumped to json then reloaded, but the `contact_vector` is lost in this transaction because the properties are not included!

**Comment by alejoe91** [comment]
Nope, check #1806 ;)

**Comment by DradeAW** [comment]
Ah!

Thank you :)
