### ISSUE TITLE
Kilosort3 Hangs

### ISSUE THREAD

**Issue by nmtimme** [SpikeInterface/spikeinterface#1910]
Hello

I'm trying to go through the guide to using spike interface to spike sort neuropixel data (https://spikeinterface.readthedocs.io/en/latest/how_to/analyse_neuropixels.html), but I'm running into an error with detect_peaks. Thank you for quickly addressing my issue with plot_traces #1899 ! I'm still working on the suggestions for the radius_um error #1907 .

I'm running version 0.98.2 on a Linux cluster with a GPU. I'm running on a virtual desktop, so I can view plots and interact with GUIs. I installed spikeinterface using miniconda 4.12.0 using this .yml file:

```
name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - mamba
  # numpy 1.22 break numba which break tridesclous
  - numpy<1.22
  # joblib 1.2 is breaking hdbscan
  - joblib=1.1
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyter
  - mpi4py
  - cxx-compiler
  - libxcb
  - pyqt=5
  - pyqtgraph
  - htop
  - ipywidgets
  - ipympl
  - pip:
    - ephyviewer
    - neo>=0.11
    - elephant>=0.10.0
    - probeinterface>=0.2.11
    - MEArec>=1.8
    - spikeinterface[full, widgets]
    - spikeinterface-gui
    - tridesclous>=1.6.6.1
    - spyking-circus>=1.1.0
    # - phy==2.0b5
```

After creating the environment, I also installed spython and cuda-python to this environment based on the page on containerized sorters (https://spikeinterface.readthedocs.io/en/latest/modules/sorters.html#containerizedsorters) and some issues I looked through. I have cudatoolkit 11.7 and singularity 3.8.3 installed also. 

I am running the following script:

```
import spikeinterface.full as si
import spikeinterface.widgets as siw
print(si.__version__)

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Define the path to the data
base_folder = Path('/NickPilotNeuropixelEphysData')
openephys_folder = base_folder / '2023-03-15_15-18-59'

# Figure out the data streams in this data set
stream_names, stream_ids = si.get_neo_streams('openephys', openephys_folder)
print('stream_names',stream_names)

# Read the data LFP data from probe A (this automatically loads the probe map)
raw_rec = si.read_openephys(openephys_folder, stream_name='Record Node 101#Neuropix-PXI-100.ProbeA-AP')
print('raw_rec',raw_rec)

# Plot the bottom part of the channel map
fig, ax = plt.subplots(figsize=(15, 10))
si.plot_probe_map(raw_rec, ax=ax, with_channel_ids=True)
ax.set_ylim(-100, 100)
# plt.show() # Uncomment to show plot

# High-pass filter the data
rec1 = si.highpass_filter(raw_rec, freq_min=300.)

# Identify bad channels and remove them
bad_channel_ids, channel_labels = si.detect_bad_channels(rec1)
rec2 = rec1.remove_channels(bad_channel_ids)
print('bad_channel_ids', bad_channel_ids)

# Phase shift the data to account for neuropixel sampling offset
rec3 = si.phase_shift(rec2)

# Common median reference the data
rec4 = si.common_reference(rec3, operator="median", reference="global")
rec = rec4
print('rec',rec)

# Look at the data across multiple steps of pre-processing (this doesn't seem to work)
# %matplotlib widget
# si.plot_timeseries({'filter':rec1, 'cmr': rec4}, backend='ipywidgets')

# Look at the rasters at various stages of preprocessing
fig, axs = plt.subplots(ncols=3, figsize=(20, 10))
si.plot_timeseries(rec1, backend='matplotlib',  clim=(-50, 50), ax=axs[0])
si.plot_timeseries(rec4, backend='matplotlib',  clim=(-50, 50), ax=axs[1])
si.plot_timeseries(rec, backend='matplotlib',  clim=(-50, 50), ax=axs[2])
for i, label in enumerate(('filter', 'cmr', 'final')):
    axs[i].set_title(label)
# plt.show() # Uncomment to show plot

# Look at some example traces
fig, ax = plt.subplots(figsize=(20, 10))
some_chans = rec.channel_ids[[100, 150, 200, ]]
si.plot_timeseries({'filter':rec1, 'cmr': rec4}, backend='matplotlib', mode='line', ax=ax, channel_ids=some_chans)
# plt.show() # Uncomment to show plot

# Save the preprocessed file (we need clean up directory structure)
# job_kwargs = dict(n_jobs=40, chunk_duration='1s', progress_bar=True)
# rec = rec.save(folder=base_folder / 'preprocess', format='binary', **job_kwargs)

# Estimate the noise on the scaled traces (microV) or on the raw one (which is in our case int16).
noise_levels_microV = si.get_noise_levels(rec, return_scaled=True)
noise_levels_int16 = si.get_noise_levels(rec, return_scaled=False)
fig, ax = plt.subplots()
_ = ax.hist(noise_levels_microV, bins=np.arange(5, 30, 2.5))
ax.set_xlabel('noise  [microV]')
# Text(0.5, 0, 'noise  [microV]')
# plt.show() # Uncomment to show plot

# # Detect and localize peaks
# from spikeinterface.sortingcomponents.peak_detection import detect_peaks
# job_kwargs = dict(n_jobs=40, chunk_duration='1s', progress_bar=True)
# peaks = detect_peaks(rec,  method='locally_exclusive', noise_levels=noise_levels_int16, detect_threshold=5, radius_um=50., **job_kwargs)
# print('peaks',peaks)
# from spikeinterface.sortingcomponents.peak_localization import localize_peaks
# peak_locations = localize_peaks(rec, peaks, method='center_of_mass', radius_um=50., **job_kwargs)
# print('peak_locations',peak_locations)

# # Visualize peaks to look for potential drift
# fs = rec.sampling_frequency
# fig, ax = plt.subplots(figsize=(10, 8))
# ax.scatter(peaks['sample_ind'] / fs, peak_locations['y'], color='k', marker='.',  alpha=0.002)
# plt.show()

# # Use peak location estimates to estimate cluster separation prior to sorting
# fig, ax = plt.subplots(figsize=(15, 10))
# si.plot_probe_map(rec, ax=ax, with_channel_ids=True)
# ax.set_ylim(-100, 150)
# ax.scatter(peak_locations['x'], peak_locations['y'], color='purple', alpha=0.002)
# plt.show()

# Do spike sorting with kilosort3

# Check the available spike sorters
availSorters = si.available_sorters()
print('availSorters',availSorters)

# Check the installed spike sorters
installedSorters = si.installed_sorters()
print('installedSorters',installedSorters)

# Check default params for kilosort3
defaultKS3Params = si.get_default_sorter_params('kilosort3')
# print('defaultKS3Params',defaultKS3Params)

# Run kilosort3
sorting = si.run_sorter('kilosort3', rec, output_folder=base_folder / 'kilosort3_output', singularity_image="spikeinterface/kilosort3-compiled-base:latest", verbose=True, **defaultKS3Params)
```

This is what I get as an output:

```
0.98.2
stream_names ['Record Node 101#Neuropix-PXI-100.ProbeA-AP', 'Record Node 101#Neuropix-PXI-100.ProbeA-LFP', 'Record Node 101#Neuropix-PXI-100.ProbeB-AP', 'Record Node 101#Neuropix-PXI-100.ProbeB-LFP']
raw_rec OpenEphysBinaryRecordingExtractor: 384 channels - 30.0kHz - 1 segments - 56,827,380 samples 
                                   1,894.25s (31.57 minutes) - int16 dtype - 40.65 GiB
bad_channel_ids ['AP192']
rec CommonReferenceRecording: 383 channels - 30.0kHz - 1 segments - 56,827,380 samples 
                          1,894.25s (31.57 minutes) - int16 dtype - 40.54 GiB
availSorters ['combinato', 'hdsort', 'herdingspikes', 'ironclust', 'kilosort', 'kilosort2', 'kilosort2_5', 'kilosort3', 'klusta', 'mountainsort4', 'mountainsort5', 'pykilosort', 'spykingcircus', 'spykingcircus2', 'tridesclous', 'tridesclous2', 'waveclus', 'waveclus_snippets', 'yass']
installedSorters ['spykingcircus', 'spykingcircus2', 'tridesclous', 'tridesclous2']
Starting container
spikeinterface is already installed in spikeinterface/kilosort3-compiled-base:latest
Installing extra requirements: ['neo']
Running kilosort3 sorter inside spikeinterface/kilosort3-compiled-base:latest
```

Then, the program just sits there. The recording is a single neuropixel 1 recording that is about 30 minutes long. I can see that a kilosort3_output folder has been created. It contains a params json file, a recording json file, and a directory that contains a matlab channel map file and a ~42GB recording.dat file. Nothing else gets created and there are no other updates in the terminal for the next ~hour, at which point the script is forced to end by the time limit on the cluster machine. If I stop it before that point, I get this output (I've checked this a few times and I always get the same thing after I wait for those files to be created):

```
^CTraceback (most recent call last):
  File "/spikeInterfaceVer1/openEphysTest1.py", line 115, in <module>
    sorting = si.run_sorter('kilosort3', rec, output_folder=base_folder / 'kilosort3_output', singularity_image="spikeinterface/kilosort3-compiled-base:latest", verbose=True, **defaultKS3Params)
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 142, in run_sorter
    return run_sorter_container(
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 555, in run_sorter_container
    res_output = container_client.run_command(cmd)
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 329, in run_command
    res = Client.execute(self.client_instance, command, options=options)
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spython/main/execute.py", line 110, in execute
    return self._run_command(
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spython/main/base/command.py", line 137, in run_command
    result = run_cmd(
  File "/.conda/envs/si_env/lib/python3.9/site-packages/spython/utils/terminal.py", line 196, in run_command
    for line in process.communicate():
  File "/.conda/envs/si_env/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/.conda/envs/si_env/lib/python3.9/subprocess.py", line 1979, in _communicate
    ready = selector.select(timeout)
  File "/.conda/envs/si_env/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
```

Given the behavior and the name of the timeout variable, I thought this might be relevant to understanding what is happening.

The machine has an nvidia A100 GPU and I think I've done what I should to make sure it is being utilized (e.g., cudatoolkit installed), but I don't know if it is being utilized. 

I don't see kilosort3 on the list of installed sorters, so perhaps I missed some step in terms of properly installing the containerized version of kilosort3?

I'd appreciate any ideas on how to figure out what is happening, address this problem, and/or determine if the GPU is being utilized. Thank you!

~Nick

**Comment by zm711** [comment]
<img width="578" alt="Screenshot 2023-08-04 at 17 59 51" src="https://github.com/SpikeInterface/spikeinterface/assets/92116279/9a7b2e89-8cff-43c5-ae24-72a15fb70fb5">
@nmtimme, I'm not super familiar with the containerized running of SI, but based on Kilosort's own metrics (https://www.biorxiv.org/content/10.1101/2023.01.07.523036v1.full.pdf+html) the time to run Kilosort3 can be quite substantial. Could you test the same file using Kilosort2 or 2.5 and see if those hang or not? Or could you book a longer appointment on your cluster? And if that doesn't work we can wait for the experts to troubleshoot further.

As far as I know Kilosort_1,2,2.5,3 will only run with GPU (ie they will completely fail if GPU is not being accessed) so if you are hanging and not explicitly erroring it seems like things should be engaging.

**Comment by nmtimme** [comment]
Hi @zm711 , thanks for that suggestion. Unfortunately, I tried it with Kilosort 2.5 and I got the same result. I let it run for about 2 hours. It hangs up at:

`Running kilosort2_5 sorter inside spikeinterface/kilosort2_5-compiled-base:latest`

No files were produced, other than those two json files, the site mapping matlab file, and the .dat file that are produced with a few minutes of starting the sorting, just like with kilosort3. Then, when I forced it to stop, I got the exact same Traceback as in my original post. I'd appreciate any other suggestions people might have. Thanks!

~Nick

**Comment by nmtimme** [comment]
I believe I have resolved the problem. I found that if I requested 128 GB of RAM on the cluster I am using, kilosort3 ran just fine in about 25 minutes. I'm not sure why failing to request a specific amount caused kilosort3 to hang up or slow way down rather than produce some sort of error, but that seems to have been the result. Thanks!

**Comment by zm711** [comment]
@nmtimme Super interesting and good to know. Now that you mention it, in the past we were running Kilosort2 locally but with data from a storage server and once when there were server upgrades our transfer speeds tanked and Kilosort2 (which normally was taking 20-30 minutes for us) ended up plodding along for 4 or 5 hours. It finally finished the run so I don't think it is actually erroring; it just works at the speed allowable by the current computer config.
