### ISSUE TITLE
Problem running sorter in containers

### ISSUE THREAD

**Issue by rdzakpasu** [SpikeInterface/spikeinterface#1919]
Hello. 
I am working through the SpikeInterface DEMO v0.95 - NeuroDataReHack - October 2022 Notebook. I've installed SpikeInterface version 0.98.2.  I have gotten to the section on running a sorter in container since I don't have a sorter installed on my computer. I changed the code to use Mountainsort5 because I don't have a GPU installed at this time. However, when I try to load and run a sorter in a container, I get the following error messages (and I've tried several sorters but get the same error). Any help is appreciated.

INPUT:
```
sorting_MS5 = ss.run_sorter('mountainsort5', recording_saved, 
                            output_folder=base_folder / 'results_MS5',
                            verbose=True, docker_image="spikeinterface/mountainsort5-base", 
                            **sorter_params)
```
OUTPUT:
```
Starting container
Installing spikeinterface==0.98.2 in spikeinterface/mountainsort5-base
Running mountainsort5 sorter inside spikeinterface/mountainsort5-base
Stopping container
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Cell In[56], line 2
      1 # run spike sorting on entire recording
----> 2 sorting_MS5 = ss.run_sorter('mountainsort5', recording_saved, 
      3                             output_folder=base_folder / 'results_MS5',
      4                             verbose=True, docker_image="spikeinterface/mountainsort5-base", 
      5                             **sorter_params)

File ~\AppData\Local\anaconda3\Lib\site-packages\spikeinterface\sorters\runsorter.py:142, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, delete_container_files, with_output, **sorter_params)
    140         else:
    141             container_image = singularity_image
--> 142     return run_sorter_container(
    143         container_image=container_image,
    144         mode=mode,
    145         **common_kwargs,
    146     )
    148 return run_sorter_local(**common_kwargs)

File ~\AppData\Local\anaconda3\Lib\site-packages\spikeinterface\sorters\runsorter.py:595, in run_sorter_container(sorter_name, recording, mode, container_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, delete_container_files, extra_requirements, **sorter_params)
    593 if run_error:
    594     if raise_error:
--> 595         raise SpikeSortingError(f"Spike sorting in {mode} failed with the following error:\n{run_sorter_output}")
    596 else:
    597     if with_output:

SpikeSortingError: Spike sorting in docker failed with the following error:
Traceback (most recent call last):
  File "/Users/rd259/in_container_sorter_script.py", line 17, in <module>
    sorting = run_sorter_local(
  File "/usr/local/lib/python3.8/site-packages/spikeinterface/sorters/runsorter.py", line 172, in run_sorter_local
    SorterClass.set_params_to_folder(recording, output_folder, sorter_params, verbose)
  File "/usr/local/lib/python3.8/site-packages/spikeinterface/sorters/basesorter.py", line 176, in set_params_to_folder
    raise AttributeError("Bad parameters: " + str(bad_params))
AttributeError: Bad parameters: ['n_jobs', 'chunk_duration', 'progress_bar']
```

**Comment by alejoe91** [comment]
Hi, as the error suggests, `mountainsort5` does not accept the `['n_jobs', 'chunk_duration', 'progress_bar']` arguments (which are in the `sorter_params`).

You should be able to run it without additional parameters:
sorting_MS5 = ss.run_sorter('mountainsort5', recording_saved, 
                            output_folder=base_folder / 'results_MS5',
                            verbose=True, docker_image="spikeinterface/mountainsort5-base")
