### ISSUE TITLE
Issues while running Spiking Cirus

### ISSUE THREAD

**Issue by farazmoradi** [SpikeInterface/spikeinterface#242]
Hi, I have run the sorting with Spiking Circus, I have reached this error: 

RUNNING SHELL SCRIPT: tmp_TDC_5/run_spykingcircus.sh
Traceback (most recent call last):
  File "/Users/faraz/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/basesorter.py", line 198, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "/Users/faraz/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/spyking_circus/spyking_circus.py", line 161, in _run_from_folder
    shell_script.start()
  File "/Users/faraz/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/utils/shellscript.py", line 83, in start
    for line in self._process.stdout:
  File "/Users/faraz/opt/anaconda3/envs/circus/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
<ipython-input-25-e5d148971dbb> in <module>
----> 1 sorting = ss.run_spykingcircus(recording=recording_cmr, output_folder='tmp_TDC_5')
      2 sorting

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/runsorter.py in run_spykingcircus(*args, **kwargs)
    334 
    335 def run_spykingcircus(*args, **kwargs):
--> 336     return run_sorter('spykingcircus', *args, **kwargs)
    337 
    338 

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/runsorter.py in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, **sorter_params)
     57                                    remove_existing_folder=remove_existing_folder,
     58                                    delete_output_folder=delete_output_folder,
---> 59                                    verbose=verbose, raise_error=raise_error, **sorter_params)
     60     else:
     61         sorting = run_sorter_docker(sorter_name, recording, docker_image, output_folder=output_folder,

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/runsorter.py in run_sorter_local(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, **sorter_params)
     78     SorterClass.set_params_to_folder(recording, output_folder, sorter_params, verbose)
     79     SorterClass.setup_recording(recording, output_folder, verbose=verbose)
---> 80     SorterClass.run_from_folder(output_folder, raise_error, verbose)
     81     sorting = SorterClass.get_result_from_folder(output_folder)
     82 

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.1-py3.6.egg/spikeinterface/sorters/basesorter.py in run_from_folder(cls, output_folder, raise_error, verbose)
    233             print(log['error_trace'])
    234             raise SpikeSortingError(
--> 235                 "Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json")
    236 
    237         return run_time

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json

**Comment by yger** [comment]
Did you found the solution?

**Comment by farazmoradi** [comment]
sorry for the late respone. I was busy. The problem still continues!

RUNNING SHELL SCRIPT: tmp_TDC_5/run_spykingcircus.sh
Traceback (most recent call last):
  File "/Users/farazmoradi/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/basesorter.py", line 198, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "/Users/farazmoradi/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/spyking_circus/spyking_circus.py", line 161, in _run_from_folder
    shell_script.start()
  File "/Users/farazmoradi/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/utils/shellscript.py", line 83, in start
    for line in self._process.stdout:
  File "/Users/farazmoradi/opt/anaconda3/envs/circus/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
<ipython-input-9-53eb83904509> in <module>
----> 1 sorting_TDC = ss.run_spykingcircus(recording=recording_cmr, output_folder='tmp_TDC_5')
      2 sorting_TDC

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/runsorter.py in run_spykingcircus(*args, **kwargs)
    334 
    335 def run_spykingcircus(*args, **kwargs):
--> 336     return run_sorter('spykingcircus', *args, **kwargs)
    337 
    338 

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/runsorter.py in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, **sorter_params)
     57                                    remove_existing_folder=remove_existing_folder,
     58                                    delete_output_folder=delete_output_folder,
---> 59                                    verbose=verbose, raise_error=raise_error, **sorter_params)
     60     else:
     61         sorting = run_sorter_docker(sorter_name, recording, docker_image, output_folder=output_folder,

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/runsorter.py in run_sorter_local(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, **sorter_params)
     78     SorterClass.set_params_to_folder(recording, output_folder, sorter_params, verbose)
     79     SorterClass.setup_recording(recording, output_folder, verbose=verbose)
---> 80     SorterClass.run_from_folder(output_folder, raise_error, verbose)
     81     sorting = SorterClass.get_result_from_folder(output_folder)
     82 

~/opt/anaconda3/envs/circus/lib/python3.6/site-packages/spikeinterface-0.90.2.dev0-py3.6.egg/spikeinterface/sorters/basesorter.py in run_from_folder(cls, output_folder, raise_error, verbose)
    233             print(log['error_trace'])
    234             raise SpikeSortingError(
--> 235                 "Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json")
    236 
    237         return run_time

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in spikeinterface_log.json

**Comment by samuelgarcia** [comment]
Can I close this ?

**Comment by farazmoradi** [comment]
Actually, I still have the problem and I did not have found the solution.

**Comment by alejoe91** [comment]
closing for lack of activity
