### ISSUE TITLE
Mountiansort5 wrapper tempdir error

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeinterface#2670]
The current `TemporaryDirectory` approach in Mountainsort5 wrapper gives the following error when running in some environments e.g. Dandihub:

```python
Error running mountainsort5
INFO:spikeinterface_pipelines.logger:Spike sorting error:
Spike sorting error trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spikeinterface/sorters/basesorter.py", line 258, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "/usr/local/lib/python3.10/site-packages/spikeinterface/sorters/external/mountainsort5.py", line 189, in _run_from_folder
    with TemporaryDirectory(dir=p["temporary_base_dir"]) as tmpdir:
  File "/usr/local/lib/python3.10/tempfile.py", line 869, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.10/tempfile.py", line 873, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "/usr/local/lib/python3.10/tempfile.py", line 855, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/local/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmpxs6r99id'
```

**Comment by zm711** [comment]
See #2607, #2489
