### ISSUE TITLE
error in toy_example() in check_your_install.py 

### ISSUE THREAD

**Issue by yilmazduygu** [SpikeInterface/spikeinterface#321]
Hi, 
I created a fresh environment using the `installation_tips`, thanks for that! But unfortunately it throws an error when I try to run `check_your_install.py`: 

`(si_env) C:\Users\menalab\Documents>python check_your_install.py
Traceback (most recent call last):
  File "check_your_install.py", line 80, in <module>
    _create_recording()
  File "check_your_install.py", line 17, in _create_recording
    rec, sorting = si.toy_example(num_segments=1, duration=200, seed=1, num_channels=16, num_columns=2)
TypeError: toy_example() got an unexpected keyword argument 'num_columns'`

**Comment by alejoe91** [comment]
Hi @yilmazduygu 

I think we didn't release that yet. Can you try to install from master?
