### ISSUE TITLE
Sorting in docker with kilosort 2 or 4 fails

### ISSUE THREAD

**Issue by jonpedros** [SpikeInterface/spikeinterface#3263]
Sorting in docker fails with Kilosort 2 or 2.5 when running it on tetrode grouped, bandpassed, rereferenced, whitened data, although it works fine with other sorters, including tridesclous and mountainsort4. A 10 minutes slice of the data is used with `BaseRecording.get_traces()`.

```python
    params = {'skip_kilosort_preprocessing': True, 
              'car': False,
              'delete_tmp_files': True}
    sorting = ss.run_sorter_by_property(sorter_name=sorter,
                                        recording=recording_preprocessed,
                                        grouping_property='group',
                                        folder=sorter_fp,
                                        docker_image=True,
                                        verbose=True,
                                        **params)
```

```python
SpikeSortingError: Spike sorting in docker failed with the following error:
/Users/systemses/Downloads/data_analysis/data/MD-mPFC-Exp/MD-mPFC-1_2024-07-04_11-17-12/Record Node 106/experiment1/recording1/spike_sorting/kilosort2_output/in_container_sorter_script.py:23: DeprecationWarning: `output_folder` is deprecated and will be removed in version 0.103.0 Please use folder instead
  sorting = run_sorter_local(
Traceback (most recent call last):
  File "/Users/systemses/Downloads/data_analysis/data/MD-mPFC-Exp/MD-mPFC-1_2024-07-04_11-17-12/Record Node 106/experiment1/recording1/spike_sorting/kilosort2_output/in_container_sorter_script.py", line 23, in <module>
    sorting = run_sorter_local(
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 275, in run_sorter_local
    SorterClass.setup_recording(recording, folder, verbose=verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 233, in setup_recording
    cls._setup_recording(recording, sorter_output_folder, sorter_params, verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosortbase.py", line 148, in _setup_recording
    padded_recording = TracePaddedRecording(
TypeError: __init__() got an unexpected keyword argument 'parent_recording'
```

And in Kilosort 4

```python
    params = {'skip_kilosort_preprocessing': True,
              'do_CAR': False,
              'do_correction': False}
```

Runtime trace:
```python
{
    "sorter_name": "kilosort4",
    "sorter_version": "4.0.12",
    "datetime": "2024-07-29T08:22:40.976628",
    "runtime_trace": [],
    "error": true,
    "error_trace": [
        "Traceback (most recent call last):",
        "  File \"/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/basesorter.py\", line 261, in run_from_folder",
        "    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)",
        "  File \"/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/external/kilosort4.py\", line 261, in _run_from_folder",
        "    st, tF, _, _ = detect_spikes(ops, device, bfile, tic0=tic0, progress_bar=progress_bar)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/run_kilosort.py\", line 481, in detect_spikes",
        "    st0, tF, ops = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/spikedetect.py\", line 204, in run",
        "    ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(",
        "                                ^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/spikedetect.py\", line 72, in extract_wPCA_wTEMP",
        "    model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)",
        "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/decomposition/_truncated_svd.py\", line 208, in fit",
        "    self.fit_transform(X)",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py\", line 313, in wrapped",
        "    data_to_wrap = f(self, X, *args, **kwargs)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/base.py\", line 1473, in wrapper",
        "    return fit_method(estimator, *args, **kwargs)",
        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/decomposition/_truncated_svd.py\", line 228, in fit_transform",
        "    X = self._validate_data(X, accept_sparse=[\"csr\", \"csc\"], ensure_min_features=2)",
        "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/base.py\", line 633, in _validate_data",
        "    out = check_array(X, input_name=\"X\", **check_params)",
        "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1082, in check_array",
        "    raise ValueError(",
        "  ValueError: Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD."
    ],
    "run_time": null
}
```

**Comment by alejoe91** [comment]
@jonpedros can you open a separate issue for KS4? I think that in that case the issue is unrelated to the `skip_kilosort_preprocessing`. Have you tried KS4 without skipping preprocessing?
