### ISSUE TITLE
SpyKingCircus2 QuickStart Tutorial Error 

### ISSUE THREAD

**Issue by ajcheng1** [SpikeInterface/spikeinterface#3334]
I am following the quickstart tutorial guide and running locally, spykingcircus2.  I got this error from running this code in my jupyter notebook
`sorting_SC2 = ss.run_sorter(sorter_name="spykingcircus2", recording=recording_preprocessed)
print(sorting_SC2)`

`   
SpikeSortingError: Spike sorting error trace:
Traceback (most recent call last):
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\sorters\basesorter.py", line 261, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\sorters\internal\spyking_circus2.py", line 146, in _run_from_folder
    recording_f = correct_motion(recording_f, **params["motion_correction"])
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\preprocessing\motion.py", line 429, in correct_motion
    motion = estimate_motion(recording, peaks, peak_locations, progress_bar=progress_bar, **estimate_motion_kwargs)
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\sortingcomponents\motion\motion_estimation.py", line 115, in estimate_motion
    motion = method_class.run(
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\sortingcomponents\motion\decentralized.py", line 147, in run
    non_rigid_windows, non_rigid_window_centers = get_spatial_windows(
  File "C:\Users\Shado\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spikeinterface\sortingcomponents\motion\motion_utils.py", line 311, in get_spatial_windows
    raise Exception(
Exception: get_spatial_windows(): win_step_um=200.0/win_scale_um=300.0/win_margin_um=-150.0 are too large for the probe size (depth range=275.0). You can try to reduce them or use rigid motion.

Spike sorting failed. You can inspect the runtime trace in C:\Users\Shado\SHJ\spykingcircus2_output/spikeinterface_log.json.
`

**Comment by yger** [comment]
The error is normal, and as said due to the geometry of the probe. Either you set apply_motion_correction=False in run_sorter(), or you change the params of the motion correction via the motion_correction params
