### ISSUE TITLE
Kilosort docker image cant install spikeinterface

### ISSUE THREAD

**Issue by arturoptophys** [SpikeInterface/spikeinterface#3502]
Hi all,
i have troubles to run sorting in docker containers for Kilosort 3 but also Kilosort 2.5
If i just run the sorter with docker_image=True

```
installation_mode='auto' switching to installation_mode: 'github'
Starting container
Installing spikeinterface with github in container
Installing neo with pypi in container
Running kilosort3 sorter inside spikeinterface/kilosort3-compiled-base
Stopping container
[2024-10-23 13:07:00,075][ERROR]: Spike sorting in docker failed with the following error:
Traceback (most recent call last):
  File "path_removed/in_container_sorter_script.py", line 4, in <module>
    from spikeinterface import load_extractor
ModuleNotFoundError: No module named 'spikeinterface'
```
switching mode to pypi doesnt solve this issue.

I tried to build modified docker image with:

```
FROM spikeinterface/kilosort3-compiled-base:latest
RUN pip install --user "spikeinterface[full] @ git+https://github.com/SpikeInterface/spikeinterface.git"
```

yet here I get the error the newest spikeinterface is not compatible with python version in container.

ERROR: Package 'spikeinterface-0.102.0' requires a different Python: 3.8.1 not in '<4.0,>=3.9'

switching to installation from pypi solved the docker build, and if i point docker_image to this build it runs.

Overall, it seems the installation_mode using github is not compatible anymore with python versions in docker containers.
However, why switching  installation_mode to pypi didn't help im not sure...

Best,
Artur

**Comment by zm711** [comment]
Where is the python 3.8 coming from? It went end of life in October of this year so we switched over to >=3.9 in main. Do you need python 3.8 for something?

**Comment by arturoptophys** [comment]
No clue, I assumed it was from docker container. I'm running 3.10.12 locally.

**Comment by zm711** [comment]
@alejoe91 knows all the docker stuff. So he can comment on this. Maybe we need to make new dockers with an appropriate python version?

**Comment by samuelgarcia** [comment]
I guess we need to rebuild kilosort with more recent pyhon.
The workaround is to install spikeinterface with the 0.101.0 version which support python 3.8
now si need python > 3.8

**Comment by Lingsheng-Meng** [comment]
> Same with pykilosort docker. Also fixable by creating custom docker and installing spikeinteface from pypi.

Same issue with herdingspikes docker.

**Comment by alejoe91** [comment]
Thanks for pinging guys! I'll update the python3.8 images over the week!

**Comment by alejoe91** [comment]
@arturoptophys I'm testing the different images and they are all Python>=3.9.

Is it possible that your local images are outdated? I would suggest removing them locally and pulling the latest image again.

- Kilosort2.5: Python 3.9.16
![image](https://github.com/user-attachments/assets/5ba8c277-2b4d-4ddd-b3f7-d7661668d27c)

- Kilosort2: Python 3.9.16
![image](https://github.com/user-attachments/assets/b20df060-afad-447d-acfd-d3cc6c3f1edd)

- Kilosort3: Python 3.9.16
![image](https://github.com/user-attachments/assets/c5dabcef-6169-433a-822d-7adb0bfd208e)

- PyKilosort: Python 3.9.17
![image](https://github.com/user-attachments/assets/5ba8dd85-e038-4e6b-9b17-2a93ceaa387f)

- HerdingSpikes (just pushed v0.4.5): Python 3.12.7
![image](https://github.com/user-attachments/assets/cf294173-7ec9-496e-a365-f62c60b3608e)

**Comment by arturoptophys** [comment]
Indeed, I have tried spike sorting some time ago and downloaded docker image back then.  running docker image ls showed the were build > year ago.

```
run -it spikeinterface/kilosort3-compiled-base:latest
root@41dbd15b9634:/# python --version
Python 3.8.1
```
Cant test pulling newest version right now as I run out of disc space on my pc :/ .. but I assume this would solve the issue. Sorry for the false alarm. 

Wouldn't it make sense to add "docker pull" if one is using "latest" image, when trying to spikesort? As this would prevent the issue of updating the spikeinterface repo but accessing old docker image, like happened to me.

**Comment by MichelleLatham** [comment]
Hi,
I'm having the same issue but with Kilosort 4. I'm running my processing pipeline on a HPC that only uses apptainer. This is the function call.

```
def spike_sorting(rec):
    params_kilosort4 = {'do_correction': False, 'singularity_image':True}
    sorter = si.run_sorter('kilosort4', rec,
                           folder=str(spikeglx_folder / 'kilosort4'),
                           verbose=True, **params_kilosort4)
    return sorter
```

and this is the error I'm getting

```
installation_mode='auto' switching to installation_mode: 'github'
docker://spikeinterface/kilosort4-base
Singularity: pulling image spikeinterface/kilosort4-base
singularity pull --name kilosort4-base.sif docker://spikeinterface/kilosort4-base
INFO:    Environment variable SINGULARITY_PULLFOLDER is set, but APPTAINER_PULLFOLDER is preferred
INFO:    Using cached SIF image
INFO:    Environment variable SINGULARITY_PULLFOLDER is set, but APPTAINER_PULLFOLDER is preferred
INFO:    Using cached SIF image
kilosort4-base.sif
Starting container
Installing spikeinterface with github in container
Installing neo with pypi in container
Running kilosort4 sorter inside spikeinterface/kilosort4-base
Stopping container
Traceback (most recent call last):
  File "/lustre/scratch/data/s87mlath_hpc-PhD/neuropixels_processing_pipeline/main.py", line 242, in <module>
    sorter = spike_sorting(rec)
             ^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/data/s87mlath_hpc-PhD/neuropixels_processing_pipeline/main.py", line 42, in spike_sorting
    sorter = si.run_sorter('kilosort4', rec,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s87mlath_hpc/.conda/envs/neuropixel/lib/python3.11/site-packages/spikeinterface/sorters/runsorter.py", line 193, in run_sorter
    return run_sorter_container(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/s87mlath_hpc/.conda/envs/neuropixel/lib/python3.11/site-packages/spikeinterface/sorters/runsorter.py", line 648, in run_sorter_container
    raise SpikeSortingError(f"Spike sorting in {mode} failed with the following error:\n{run_sorter_output}")
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting in singularity failed with the following error:
Traceback (most recent call last):
  File "/lustre/scratch/data/s87mlath_hpc-PhD/neuropixel_recordings/20260223_N20_exvivo_cortex_g0/20260223_exvivo_cortex_g0_imec0/in_container_sorter_script.py", line 4, in <module>
    from spikeinterface import load_extractor
ModuleNotFoundError: No module named 'spikeinterface'
```

Is it still a problem with having an old container image? I've tried to downgrade spikeinterface to an earlier version (0.101.0) but I'm still getting the same error. Before I was using version 0.102.3

**Comment by alejoe91** [comment]
Hi @MichelleLatham 

The docker images come without a SpikeInterface installation on purpose, since they can be used as "external" images from a normal python installation. If you want to run that code standalone, you can make a new Dockerfile adding spikeinterface:
```
FROM spikeinterface/kilosort4-base:latest

RUN pip install spikeinterface==0.103.2
```
