### ISSUE TITLE
`kilosort3` not detected in Docker container

### ISSUE THREAD

**Issue by caniko** [SpikeInterface/spikeinterface#475]
I tried running `kilosort3` through the docker image on the tutorial dataset. Python in the container fails to detect `kilosort3`.

Snippet:
``` python
sorting_kilosort = ss.run_kilosort3( 
    recording=recording_preprocessed,
    output_folder="kilosort3_output",
    docker_image="spikeinterface/kilosort3-base:0.1.0"
)
```

Output:
``` shell
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Input In [15], in <module>
----> 1 sorting_TDC = ss.run_kilosort3( 
      2     recording=recording_preprocessed,
      3     output_folder="kilosort3_output",
      4     docker_image="spikeinterface/kilosort3-base:0.1.0"
      5 )

File ~/.pyenv/versions/3.9.9/envs/spikeinterface/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:370, in run_kilosort3(*args, **kwargs)
    369 def run_kilosort3(*args, **kwargs):
--> 370     return run_sorter('kilosort3', *args, **kwargs)

File ~/.pyenv/versions/3.9.9/envs/spikeinterface/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:63, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, with_output, **sorter_params)
     57     sorting = run_sorter_local(sorter_name, recording, output_folder=output_folder,
     58                                remove_existing_folder=remove_existing_folder,
     59                                delete_output_folder=delete_output_folder,
     60                                verbose=verbose, raise_error=raise_error, with_output=with_output,
     61                                **sorter_params)
     62 else:
---> 63     sorting = run_sorter_docker(sorter_name, recording, docker_image, output_folder=output_folder,
     64                                 remove_existing_folder=remove_existing_folder,
     65                                 delete_output_folder=delete_output_folder,
     66                                 verbose=verbose, raise_error=raise_error,
     67                                 with_output=with_output, **sorter_params)
     68 return sorting

File ~/.pyenv/versions/3.9.9/envs/spikeinterface/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:267, in run_sorter_docker(sorter_name, recording, docker_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, **sorter_params)
    265 if run_error:
    266     if raise_error:
--> 267         raise SpikeSortingError(
    268             f"Spike sorting in docker failed with the following error:\n{run_sorter_output}")
    269 else:
    270     if with_output:

Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/home/can/Projects/spikeinterface/in_docker_sorter_script.py", line 15, in <module>

run_sorter_local(\'kilosort3\', recording, output_folder=output_folder,
File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/runsorter.py", line 81, in run_sorter_local

output_folder = SorterClass.initialize_folder(
    File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/basesorter.py", line 81, in initialize_folder
    raise Exception(f"The sorter {cls.sorter_name} is not installed."
    Exception: The sorter kilosort3 is not installed.Please install it with:
    
    To use Kilosort3 run:
    
    >>> git clone https://github.com/MouseLand/Kilosort
    and provide the installation path by setting the KILOSORT3_PATH
    environment variables or using Kilosort3Sorter.set_kilosort3_path().
    
    More information on Kilosort3 at:
    https://github.com/MouseLand/Kilosort'
```

**Comment by samuelgarcia** [comment]
I don't think docker for KS are functional yet.
Please also open an issue here : https://github.com/SpikeInterface/spikeinterface-dockerfiles
@magland : any news on docker for KS ?
