### ISSUE TITLE
General issues with the easy install in Ubuntu 20.04

### ISSUE THREAD

**Issue by matiasandina** [SpikeInterface/spikeinterface#482]
Hello,
I am sorry if you prefer to chunk this in multiple issues, I thought it would be convenient to go at it all together, since I have solved some of them. I am happy to chunk it and add some suggestions/PR if you want me to.

### First check

I am trying to follow the install in `Ubuntu 20.04`. I created an environment using `conda` and the windows `.yml` file provided for the easy installations. I did this because I ran into some of this issues while installing in Windows (currently the only machine where we have a GPU with Kilosort) and I wanted to see if I could go all the way through in my linux machine. Running the python script to check the install I got:

```
write_binary_recording with n_jobs 1  chunk_size None
Import spikeinterface ...OK
Import spikeinterface.full ...OK
Run tridesclous ...OK
RUNNING SHELL SCRIPT: spykingcircus_output/run_spykingcircus.sh
Run spykingcircus ...OK
Run herdingspikes ...Fail
Open spikeinterface-gui ...Fail
Setting 'return_scaled' to False
Export to phy ...OK
Traceback (most recent call last):
  File "/home/matias/miniconda3/envs/si_env/bin/phy", line 5, in <module>
    from phy.apps import phycli
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/apps/__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/__init__.py", line 6, in <module>
    from .qt import (
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/qt.py", line 41, in <module>
    from PyQt5.QtWebEngineWidgets import (QWebEngineView,  # noqa
ImportError: /home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/PyQt5/../../../libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5
Open phy ...OK

```
It seems that most things went fine, although a few issues. After

```
(si_env) matias@work:~/$ pip install herdingspikes
``` 
### herdingspikes

It looks like `herdingspikes` is now working on the check.

```
write_binary_recording with n_jobs 1  chunk_size None
Import spikeinterface ...OK
Import spikeinterface.full ...OK
Run tridesclous ...OK
RUNNING SHELL SCRIPT: spykingcircus_output/run_spykingcircus.sh
Run spykingcircus ...OK
# Generating new position and neighbor files from data file
# Not Masking any Channels
# Sampling rate: 30000
# Localization On
# Number of recorded channels: 16
# Few recording channels: not subtracing mean from activity
# Analysing frames: 6000000; Seconds: 200.0
# Frames before spike in cutout: 9
# Frames after spike in cutout: 54
# tcuts: 39 84
# tInc: 100000
# Detection completed, time taken: 0:00:02.426973
# Time per frame: 0:00:00.000404
# Time per sample: 0:00:00.000025
Loaded 3617 spikes.
Fitting dimensionality reduction using all spikes...
...projecting...
...done
Clustering...
Clustering 3617 spikes...
number of seeds: 47
seeds/job: 2
using 24 cpus
[Parallel(n_jobs=24)]: Using backend LokyBackend with 24 concurrent workers.
[Parallel(n_jobs=24)]: Done   3 out of  24 | elapsed:    1.3s remaining:    8.9s
[Parallel(n_jobs=24)]: Done  16 out of  24 | elapsed:    1.5s remaining:    0.8s
[Parallel(n_jobs=24)]: Done  24 out of  24 | elapsed:    1.6s finished
Number of estimated units: 8
Run herdingspikes ...OK
Open spikeinterface-gui ...Fail
Setting 'return_scaled' to False
Export to phy ...OK
Traceback (most recent call last):
  File "/home/matias/miniconda3/envs/si_env/bin/phy", line 5, in <module>
    from phy.apps import phycli
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/apps/__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/__init__.py", line 6, in <module>
    from .qt import (
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/qt.py", line 41, in <module>
    from PyQt5.QtWebEngineWidgets import (QWebEngineView,  # noqa
ImportError: /home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/PyQt5/../../../libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5
Open phy ...OK

```
### spikeinterface-gui

To solve this issue I tried to import the gui. I got this exact error in both Windows and Ubuntu.

```
>>> import spikeinterface_gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/spikeinterface_gui/__init__.py", line 8, in <module>
    from .mainwindow import MainWindow
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/spikeinterface_gui/mainwindow.py", line 4, in <module>
    from .controller import SpikeinterfaceController
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/spikeinterface_gui/controller.py", line 7, in <module>
    from spikeinterface.toolkit import (get_template_extremum_channel, get_template_channel_sparsity,
ImportError: cannot import name 'compute_unit_centers_of_mass' from 'spikeinterface.toolkit' (/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/spikeinterface/toolkit/__init__.py)
```
I tried to diagnose the problem by checking [here](https://github.com/SpikeInterface/spikeinterface/blob/master/doc/api.rst), where `compute_unit_centers_of_mass` is listed under `spikeinterface.toolkit.postprocessing`.

But I failed to find it while actively looking for it. I cannot pinpoint the place where it's trying to be used in the code that runs the GUI, but is it possible that this is the issue?

```
>>> dir(si.toolkit.postprocessing)
['WaveformPrincipalComponent', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'calculate_template_metrics', 'compute_center_of_mass', 'compute_correlograms', 'compute_principal_components', 'compute_template_similarity', 'correlograms', 'get_spike_amplitudes', 'get_template_amplitudes', 'get_template_channel_sparsity', 'get_template_extremum_amplitude', 'get_template_extremum_channel', 'get_template_extremum_channel_peak_shift', 'get_template_metric_names', 'localize_unit', 'principal_component', 'spike_amplitudes', 'template_metrics', 'template_similarity', 'template_tools', 'unit_localization']
>>> 'compute_unit_centers_of_mass' in dir(si.toolkit.postprocessing)
False

```

### Phy

Although phy is passing the check, I cannot launch it 

```
(si_env) matias@work:~/$ phy template-gui params.py 
Traceback (most recent call last):
  File "/home/matias/miniconda3/envs/si_env/bin/phy", line 5, in <module>
    from phy.apps import phycli
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/apps/__init__.py", line 22, in <module>
    from phy.gui.qt import QtDialogLogger
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/__init__.py", line 6, in <module>
    from .qt import (
  File "/home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/phy/gui/qt.py", line 41, in <module>
    from PyQt5.QtWebEngineWidgets import (QWebEngineView,  # noqa
ImportError: /home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/PyQt5/../../../libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5

```
To solve this particular one, I added `PyQtWebEngine==5.12` to the yaml and did `pip install PyQtWebEngine==5.12` to get it.
Still, it didn't go all the way through, I met another error that boiled down to:

```
>>> import PyQt5
>>> from PyQt5.QtWebEngineWidgets import QWebEngineView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory
```
This was solved at the level of system libraries. Turns out I had this `libqt5` but was missing some.

```
(si_env) matias@work:~/$ sudo dpkg -l | grep libqt5
ii  libqt5core5a:amd64                            5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 core module
ii  libqt5dbus5:amd64                             5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 D-Bus module
ii  libqt5network5:amd64                          5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 network module

```
I installed the missing with `sudo apt-get install libqt5gui5 libqt5quickwidgets5` until I got

```
(si_env) matias@work:~/$ sudo dpkg -l | grep libqt5
ii  libqt5core5a:amd64                            5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 core module
ii  libqt5dbus5:amd64                             5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                              5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 GUI module
ii  libqt5network5:amd64                          5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 network module
ii  libqt5qml5:amd64                              5.12.8-0ubuntu1                       amd64        Qt 5 QML module
ii  libqt5quick5:amd64                            5.12.8-0ubuntu1                       amd64        Qt 5 Quick library
ii  libqt5quickwidgets5:amd64                     5.12.8-0ubuntu1                       amd64        Qt 5 Quick Widgets library
ii  libqt5svg5:amd64                              5.12.8-0ubuntu1                       amd64        Qt 5 SVG module
ii  libqt5widgets5:amd64                          5.12.8+dfsg-0ubuntu2.1                amd64        Qt 5 widgets module

```

Not sure why, but I'm still not all the way through with this

```
>>> import PyQt5
>>> from PyQt5.QtWebEngineWidgets import QWebEngineView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/matias/miniconda3/envs/si_env/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz, version Qt_5
```
I would understand if this was an issue with phys but I can run the same command from a `phys` environment created for a previous installation of `phy` in both Windows 10 and Ubuntu 20.04. Any help appreciated!

### Cleaning

Inside `folders`, the `def_clean()` function is missing `herdingspikes_waveforms` & `herdingspikes_outputs`

```
def _clean():
    # clean
    folders = [
        'toy_example_recording',
        "tridesclous_output", "tridesclous_waveforms",
        "spykingcircus_output", "spykingcircus_waveforms",
        "phy_example"
    ]
    for folder in folders:
        if Path(folder).exists():
            shutil.rmtree(folder)
```
I would also appreciate if there was an option to avoid deleting all folders. Something quick and dirty like this might do:

```
keep_things = input("Do you want to keep installation check folders [y/n]? :> ")
if keep_things.lower() == 'yes'  or 'y':
    print("Keeping folders generated by installation check")
    return
else:
    # clean
    ...
``` 

I am happy to submit PR of any of this. Thank you for your work in this project!

**Comment by samuelgarcia** [comment]
Hello.
Thanks for report.


About the installation pf **herdingspikes**.
Yes, i think that herdingspikes need to have numpy already installed.
So the first install in the yaml do not work.
You should ask to the dev of herdingspikes.


About **spikeinterface-gui** issue : if you want it to work properly, for now you should work from source for both spikeinterface and spikeinterface-gui. We plan a release soon. For this maybe you should also install pyside instead of PyQt5 but in that case phy won't work.


Generally this **installation_tips** folder is more for windows/osx users.
For ubuntu user, we recommand apt + pip to solve installation problem because it is what we do so it is easier to tests.
Maybe it could be usefull to have a  specific readme for that. A general bash script to install everything for ubuntu sounds difficult because the way users handle python in ubuntu is ultra diverse (conda vs pip + apt, vitualenv vs venv, ...).
So maybe if you want to make a PR you could make a **installation_in_ubuntu.md** file.
And maybe you could make this file in 2 parts : install from release and install from source.

**Comment by alejoe91** [comment]
closed for inactivity
