### ISSUE TITLE
the error when get the results of  sorting

### ISSUE THREAD

**Issue by jkb521** [SpikeInterface/spikeinterface#608]
kilosort3 run time 353.29s
Traceback (most recent call last):
  File "/home/software/python3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-127-2e0d4cf81c2b>", line 5, in <cell line: 5>
    sortingk = ss.run_sorter('kilosort3', rec_cmr, output_folder=foldername,
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 67, in run_sorter
    return run_sorter_local(sorter_name, recording, output_folder=output_folder,
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 91, in run_sorter_local
    sorting = SorterClass.get_result_from_folder(output_folder)
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 258, in get_result_from_folder
    recording = load_extractor(output_folder / 'spikeinterface_recording.json')
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/core/base.py", line 821, in load_extractor
    def _load_extractor_from_dict(dic):
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/core/base.py", line 513, in load
    return extractor
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/core/base.py", line 340, in from_dict
    folder_metadata = d.get('folder_metadata', None)
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/core/base.py", line 767, in _load_extractor_from_dict
    for path in d[k]:
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/toolkit/preprocessing/common_reference.py", line 87, in __init__
    groups = [self.ids_to_indices(g) for g in groups]
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/toolkit/preprocessing/common_reference.py", line 87, in <listcomp>
    groups = [self.ids_to_indices(g) for g in groups]
  File "/home/software/python3/lib/python3.9/site-packages/spikeinterface/core/base.py", line 89, in ids_to_indices
    indices = np.array([_main_ids.index(id) for id in ids])
ValueError: 0 is not in list

**Comment by alejoe91** [comment]
Hi @jkb521 

sorry for our very late reply. Could you provide some more info? What is the code you are running? How are you preprocessing the data?
