### ISSUE TITLE
compare_sorter_to_ground_truth fails: 'object' has no attribute 'dtype'

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spikeinterface#643]
Hi,

I'm trying to benchmark some spike sorters using `spikeinterface.comparison` with a `MEArec` recording.

Here is my code:
```python
import numpy as np
import spikeinterface.comparison as sc
import spikeinterface.extractors as se


recording	= se.MEArecRecordingExtractor("/mnt/raid0/data/MEArec/recording_neuropixels_30m_200cells.h5")
sorting_true	= se.MEArecSortingExtractor("/mnt/raid0/data/MEArec/recording_neuropixels_30m_200cells.h5")
sorting		= se.PhySortingExtractor("/mnt/raid0/data/MEArec/kilosort2_default")	

comparison = sc.compare_sorter_to_ground_truth(sorting_true, sorting, delta_time=0.2, match_score=0.4, exhaustive_gt=True, n_jobs=12)

print(comparison.match_event_count)
print(comparison.agreement_scores)	
```

I get the following error:
```
Traceback (most recent call last):
  File "compare.py", line 10, in <module>
    comparison = sc.compare_sorter_to_ground_truth(sorting_true, sorting, delta_time=0.2, match_score=0.4, exhaustive_gt=True, n_jobs=12)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/comparison/paircomparisons.py", line 601, in compare_sorter_to_ground_truth
    return GroundTruthComparison(*args, **kwargs)
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/comparison/paircomparisons.py", line 241, in __init__
    self._do_count()
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/comparison/paircomparisons.py", line 280, in _do_count
    self.count_score = do_count_score(self.event_counts1, self.event_counts2,
  File "/export/home1/users/nsr/wyngaard/dev/spikeinterface/spikeinterface/spikeinterface/comparison/comparisontools.py", line 573, in do_count_score
    count_score = pd.DataFrame(index=unit1_ids, columns=columns)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/dtypes/cast.py", line 1229, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```

I checked in `comparisontools.py` on line 570, and the variable `unit1_ids` looks like this:
```python
Index(['#0', '#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9',
       ...
       '#190', '#191', '#192', '#193', '#194', '#195', '#196', '#197', '#198',
       '#199'],
      dtype='object', length=200)
shape = (200,)
dtype = object
```

I don't know much about `pandas` (never used it), but I'm guessing the error comes from the strange `dtype` of `unit1_ids`.

Thanks,
Aurélien W.

**Comment by Dradeliomecus** [comment]
Fixed by upgrading my `pandas` library (it was over 2 and a half years old).
