### ISSUE TITLE
how to solve "spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in tmp_KL/spikeinterface_log.json"

### ISSUE THREAD

**Issue by dongyangTHU** [SpikeInterface/spikeinterface#670]
When running the programme, it comes out with:
```
Traceback (most recent call last):
  File "C:\Users\22100\Desktop\spikesorting\ProjectSpikeSorting\Sorter\readzip.py", line 29, in <module>
    Neurons_list[i] = raw.sort_by(sortername)
  File "C:\Users\22100\Desktop\spikesorting\ProjectSpikeSorting\Sorter\ddlraw.py", line 104, in sort_by
    neurons = ddlsorters.Sorter(self,sortername)
  File "C:\Users\22100\Desktop\spikesorting\ProjectSpikeSorting\Sorter\ddlsorters.py", line 23, in Sorter
    sorting = ss.run_klusta(recording, output_folder='tmp_KL')
  File "C:\Users\22100\PycharmProjects\pythonProject\venv\lib\site-packages\spikeinterface\sorters\runsorter.py", line 405, in run_klusta
    return run_sorter('klusta', *args, **kwargs)
  File "C:\Users\22100\PycharmProjects\pythonProject\venv\lib\site-packages\spikeinterface\sorters\runsorter.py", line 67, in run_sorter
    return run_sorter_local(sorter_name, recording, output_folder=output_folder,
  File "C:\Users\22100\PycharmProjects\pythonProject\venv\lib\site-packages\spikeinterface\sorters\runsorter.py", line 89, in run_sorter_local
    SorterClass.run_from_folder(output_folder, raise_error, verbose)
  File "C:\Users\22100\PycharmProjects\pythonProject\venv\lib\site-packages\spikeinterface\sorters\basesorter.py", line 236, in run_from_folder
    raise SpikeSortingError(
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in tmp_KL/spikeinterface_log.json
```
But ran successfully in another PC, how to deal with this?

**Comment by alejoe91** [comment]
Hi, you can check the `spikeinterface_log.json` file in the output folder to see where it failed. Maybe there were some installation issues
