### ISSUE TITLE
Kilosort error:  sgemm in CUBLAS failed

### ISSUE THREAD

**Issue by phanhuynh** [SpikeInterface/spikeinterface#702]
Hello Spikeinterface team, thank you in advance for all your support!

So I'm getting this error when running Kilosort3:
(Matlab R2018a, CUDA 9.0, Visual Studio 2015, NVIDIA RTX A5000)
```
KilosortBase._run_from_folder <class 'spikeinterface.sorters.kilosort3.kilosort3.Kilosort3Sorter'>
RUNNING SHELL SCRIPT: _output_KS3\run_kilosort3.bat
Traceback (most recent call last):
  File "C:\Users\huynh\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\basesorter.py", line 200, in run_from_folder
    SorterClass._run_from_folder(output_folder, sorter_params, verbose)
  File "C:\Users\huynh\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\kilosortbase.py", line 42, in _run_from_folder
    raise Exception(f'{cls.sorter_name} returned a non-zero exit code')
Exception: kilosort3 returned a non-zero exit code

---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Input In [16], in <cell line: 2>()
      1 start_time = time.time()
----> 2 sorting_KS3 = ss.run_sorter('kilosort3', recording_saved, output_folder= '_output_KS3')
      3 print("--- _output_KS3 took %s seconds ---" % (time.time() - start_time))
      4 print(f'Kilosort3 found {len(sorting_KS3.get_unit_ids())} units')

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\runsorter.py:67, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, with_output, **sorter_params)
     61 if singularity_image is not None:
     62     return run_sorter_container(sorter_name, recording, 'singularity', singularity_image,
     63                                 output_folder=output_folder,
     64                                 remove_existing_folder=remove_existing_folder,
     65                                 delete_output_folder=delete_output_folder, verbose=verbose,
     66                                 raise_error=raise_error, with_output=with_output, **sorter_params)
---> 67 return run_sorter_local(sorter_name, recording, output_folder=output_folder,
     68                         remove_existing_folder=remove_existing_folder,
     69                         delete_output_folder=delete_output_folder,
     70                         verbose=verbose, raise_error=raise_error, with_output=with_output,
     71                         **sorter_params)

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\runsorter.py:89, in run_sorter_local(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, **sorter_params)
     86 SorterClass.set_params_to_folder(
     87     recording, output_folder, sorter_params, verbose)
     88 SorterClass.setup_recording(recording, output_folder, verbose=verbose)
---> 89 SorterClass.run_from_folder(output_folder, raise_error, verbose)
     90 if with_output:
     91     sorting = SorterClass.get_result_from_folder(output_folder)

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\basesorter.py:236, in BaseSorter.run_from_folder(cls, output_folder, raise_error, verbose)
    234 if has_error and raise_error:
    235     print(log['error_trace'])
--> 236     raise SpikeSortingError(
    237         f"Spike sorting failed. You can inspect the runtime trace in {output_folder}/spikeinterface_log.json")
    239 return run_time

SpikeSortingError: Spike sorting failed. You can inspect the runtime trace in _output_KS3/spikeinterface_log.json
```
Here's the log:  
[spikeinterface_log.txt](https://github.com/SpikeInterface/spikeinterface/files/8891602/spikeinterface_log.txt)

Note that:
1) I've successfully ran mexGPUall.m
2) when I run mex -setup C++, I get:  MEX configured to use 'Microsoft Visual C++ 2015' for C++ language compilation. 
3) the kilosort GUI seems to work
4) one RED flag is when I run kilosort3_master.m, I get: 
`errString =    'kilosort repo not found, or inaccessible.'`

Thank you so much!

**Comment by bendichter** [comment]
@phanhuynh would you be open to trying our kilosort docker/singiularity container with a pre-compiled version of kilosort3? Are you on a system that can run docker or singularity?

**Comment by phanhuynh** [comment]
I would love to try!  I'm installing docker now.

**Comment by bendichter** [comment]
try:
```python
ss.run_kilosort3(
    recording,
    docker_image="kilosort3-compiled-base",
    verbose=True,
)
```

**Comment by phanhuynh** [comment]
Bear with me, Ben, I'm not a programmer.  

---------------------------------------------------------------------------
```
AssertionError                            Traceback (most recent call last)
Input In [17], in <cell line: 1>()
----> 1 ss.run_kilosort3(
      2     recording,
      3     docker_image="spikeinterface/kilosort3-compiled-base",
      4     verbose=True,
      5 )

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\runsorter.py:454, in run_kilosort3(*args, **kwargs)
    453 def run_kilosort3(*args, **kwargs):
--> 454     return run_sorter('kilosort3', *args, **kwargs)

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\runsorter.py:56, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, with_output, **sorter_params)
     49 """
     50 Generic function to run a sorter via function approach.
     51 
     52 >>> sorting = run_sorter('tridesclous', recording)
     53 """ + _common_param_doc
     55 if docker_image is not None:
---> 56     return run_sorter_container(sorter_name, recording, 'docker', docker_image,
     57                                 output_folder=output_folder,
     58                                 remove_existing_folder=remove_existing_folder,
     59                                 delete_output_folder=delete_output_folder, verbose=verbose,
     60                                 raise_error=raise_error, with_output=with_output, **sorter_params)
     61 if singularity_image is not None:
     62     return run_sorter_container(sorter_name, recording, 'singularity', singularity_image,
     63                                 output_folder=output_folder,
     64                                 remove_existing_folder=remove_existing_folder,
     65                                 delete_output_folder=delete_output_folder, verbose=verbose,
     66                                 raise_error=raise_error, with_output=with_output, **sorter_params)

File ~\.conda\envs\si_env\lib\site-packages\spikeinterface\sorters\runsorter.py:222, in run_sorter_container(sorter_name, recording, mode, container_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, **sorter_params)
    217 def run_sorter_container(sorter_name, recording, mode, container_image, output_folder=None,
    218                          remove_existing_folder=True, delete_output_folder=False,
    219                          verbose=False, raise_error=True, with_output=True, **sorter_params):
    220     # common code for docker and singularity
--> 222     assert platform.system() in ('Linux', 'Darwin'), \
    223         'run_sorter() with docker is supported only on linux/macos platform '
    225     if output_folder is None:
    226         output_folder = sorter_name + '_output'

AssertionError: run_sorter() with docker is supported only on linux/macos platform 
```

**Comment by alejoe91** [comment]
Thanks Ben! I small bug was introduced during the multiple merges last wee, so we have to install from this branch: https://github.com/SpikeInterface/spikeinterface/pull/701

**Comment by alejoe91** [comment]
ok now merged to master: https://github.com/SpikeInterface/spikeinterface/pull/703

@phanhuynh can you try to install as Ben suggested?

**Comment by phanhuynh** [comment]
Good afternoon, gentlemen!  Thank you again for all your support. 
I've had a few issues but now it seems to be running.  I will follow up as soon as it finishes!

```
Docker: pulling image spikeinterface/kilosort3-compiled-base
Starting container
Installing spikeinterface from sources in spikeinterface/kilosort3-compiled-base
Installing dev spikeinterface from remote repository
Installing extra requirements: []
Running kilosort3 sorter inside spikeinterface/kilosort3-compiled-base
```

**Comment by phanhuynh** [comment]
One last question:  what other sorters do you have dockerized?

**Comment by bendichter** [comment]
https://github.com/SpikeInterface/spikeinterface/blob/3459d477cc0ea48aa7020f2b5951e79541a4d761/spikeinterface/sorters/runsorter.py#L14-L32

We are very close to also adding Waveclus and HDSort

**Comment by phanhuynh** [comment]
Sorry, a few more questions:

a) is there any downside to docker?  ie. is there any advantage to installing the sorters locally?

b) (unrelated) is there a way to call a variable once I've closed a jupyter session?  What happened was that I ran the sorter:  
sorting_KS3 = ss.run_kilosort3(recording_saved, output_folder= '_output_KS3'...)
and it successfully created the _output_KS3 folder.
But I did not run dill.dump_session(...)
Now, I've reopened Jupyter and I want to call sorting_KS3 without running the sorter again.  Thoughts?

**Comment by alejoe91** [comment]
You can do: `sortimg"KS3 = se.read_kilosort(output_KS3)`

**Comment by phanhuynh** [comment]
Thank you so much!  I don't see a similar attribute for ironclust.  Am I missing it?

**Comment by alejoe91** [comment]
Ironclust uses the `read_mda` function. A more general way to do it is: 
`ss.sorter_dict[sorter_name].read_from_folder(output_folder)` ;)

**Comment by alejoe91** [comment]
Ahahah I'm pretty sure we'll meet ata conference sooner or later :)

**Comment by phanhuynh** [comment]
Shoot, another hiccup...
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [23], in <cell line: 1>()
----> 1 sorting_IC = ss.sorter_dict['ironclust'].read_from_folder('C:/Users/huynh/spike_epsztein/proj_louis/_output_IC')

AttributeError: type object 'IronClustSorter' has no attribute 'read_from_folder'
```

**Comment by phanhuynh** [comment]
Hello again, 
Due to some other errors, I had to reinstall anaconda and recreate my environments.  
Now, I'm running into a new docker error:
(I have pywin==227, but I've also tried 226 and 228 without success.
I've also tried instsalling pypiwin32 without success)  
---------------------------------------------------------------------------
```
NameError                                 Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python39\site-packages\docker\api\client.py:159, in APIClient.__init__(self, base_url, version, timeout, tls, user_agent, num_pools, credstore_env, use_ssh_client, max_pool_size)
    158 try:
--> 159     self._custom_adapter = NpipeHTTPAdapter(
    160         base_url, timeout, pool_connections=num_pools,
    161         max_pool_size=max_pool_size
    162     )
    163 except NameError:

NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

DockerException                           Traceback (most recent call last)
Input In [33], in <cell line: 14>()
      1 ### Option 1: Run local sorter (not working) ##################
      2 # default_TDC_params = ss.TridesclousSorter.default_params()
      3 # default_TDC_params['detect_threshold'] = threshold
   (...)
     11 
     12 ### Option 2: run sorter directly from docker (preferred) ###
     13 start_time = time.time()
---> 14 sorting_TDC = ss.run_sorter(
     15     'tridesclous',
     16     recording_saved,
     17     output_folder= '_output_TDC',
     18     remove_existing_folder=True,
     19     detect_threshold=threshold,
     20     docker_image="spikeinterface/tridesclous-base", 
     21     verbose=True,
     22 )
     23 print("--- _output_TDC took %s seconds ---" % (time.time() - start_time))
     24 print(f'Tridesclous found {len(sorting_TDC.get_unit_ids())} units')

File ~\Anaconda3\envs\sienv\lib\site-packages\spikeinterface\sorters\runsorter.py:131, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, with_output, **sorter_params)
    129         else:
    130             container_image = singularity_image
--> 131     return run_sorter_container(
    132         container_image=container_image,
    133         mode=mode,
    134         **common_kwargs,
    135     )
    137 return run_sorter_local(**common_kwargs)

File ~\Anaconda3\envs\sienv\lib\site-packages\spikeinterface\sorters\runsorter.py:464, in run_sorter_container(sorter_name, recording, mode, container_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, extra_requirements, **sorter_params)
    460     else:
    461         # TODO: make opencl machanism
    462         raise NotImplementedError("Only nvidia support is available")
--> 464 container_client = ContainerClient(mode, container_image, volumes, extra_kwargs)
    465 if verbose:
    466     print('Starting container')

File ~\Anaconda3\envs\sienv\lib\site-packages\spikeinterface\sorters\runsorter.py:235, in ContainerClient.__init__(self, mode, container_image, volumes, extra_kwargs)
    233 if not HAS_DOCKER:
    234     raise ModuleNotFoundError("No module named 'docker'")
--> 235 client = docker.from_env()
    236 if container_requires_gpu is not None:
    237     extra_kwargs.pop('container_requires_gpu')

File ~\AppData\Roaming\Python\Python39\site-packages\docker\client.py:96, in DockerClient.from_env(cls, **kwargs)
     94 version = kwargs.pop('version', None)
     95 use_ssh_client = kwargs.pop('use_ssh_client', False)
---> 96 return cls(
     97     timeout=timeout,
     98     max_pool_size=max_pool_size,
     99     version=version,
    100     use_ssh_client=use_ssh_client,
    101     **kwargs_from_env(**kwargs)
    102 )

File ~\AppData\Roaming\Python\Python39\site-packages\docker\client.py:45, in DockerClient.__init__(self, *args, **kwargs)
     44 def __init__(self, *args, **kwargs):
---> 45     self.api = APIClient(*args, **kwargs)

File ~\AppData\Roaming\Python\Python39\site-packages\docker\api\client.py:164, in APIClient.__init__(self, base_url, version, timeout, tls, user_agent, num_pools, credstore_env, use_ssh_client, max_pool_size)
    159     self._custom_adapter = NpipeHTTPAdapter(
    160         base_url, timeout, pool_connections=num_pools,
    161         max_pool_size=max_pool_size
    162     )
    163 except NameError:
--> 164     raise DockerException(
    165         'Install pypiwin32 package to enable npipe:// support'
    166     )
    167 self.mount('http+docker://', self._custom_adapter)
    168 self.base_url = 'http+docker://localnpipe'

DockerException: Install pypiwin32 package to enable npipe:// support
```

**Comment by alejoe91** [comment]
Hi @phanhuynh 

You should be able to fix it with:
```
python C:/Users/<your-user-name>/Anaconda3/envs/si/Scripts/pywin32_postinstall.py -install
```

**Comment by phanhuynh** [comment]
Thanks @alejoe91!  I'm getting this error (EVEN IN ADMINISTRATOR mode of anaconda):
```
(sienv) C:\Users\huynh\Anaconda3\envs\sienv\Scripts>python pywin32_postinstall.py -install
Parsed arguments are: Namespace(install=True, remove=False, wait=None, silent=False, quiet=False, destination='C:\\Users\\huynh\\Anaconda3\\envs\\sienv\\Lib\\site-packages')
Copied pythoncom39.dll to C:\Windows\system32\pythoncom39.dll
Traceback (most recent call last):
  File "C:\Users\huynh\Anaconda3\envs\sienv\Scripts\pywin32_postinstall.py", line 633, in <module>
    install(args.destination)
  File "C:\Users\huynh\Anaconda3\envs\sienv\Scripts\pywin32_postinstall.py", line 363, in install
    os.unlink(bad_fname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\huynh\\Anaconda3\\envs\\sienv\\pythoncom39.dll'
```

**Comment by phanhuynh** [comment]
It seems that problem went away somehow (I may have done something without realizing).
Now there's a brand new issue...
(I'm so sorry -- but, as always, thank you!)

```
Starting container
Installing spikeinterface from sources in spikeinterface/tridesclous-base
Installing dev spikeinterface from remote repository
Installing extra requirements: ['neo']
Running tridesclous sorter inside spikeinterface/tridesclous-base
Stopping container
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Input In [7], in <cell line: 14>()
      1 ### Option 1: Run local sorter (not working) ##################
      2 # default_TDC_params = ss.TridesclousSorter.default_params()
      3 # default_TDC_params['detect_threshold'] = threshold
   (...)
     11 
     12 ### Option 2: run sorter directly from docker (preferred) ###
     13 start_time = time.time()
---> 14 sorting_TDC = ss.run_sorter(
     15     'tridesclous',
     16     recording_saved,
     17     output_folder= '_output_TDC',
     18     remove_existing_folder=True,
     19     detect_threshold=threshold,
     20     docker_image="spikeinterface/tridesclous-base", 
     21     verbose=True,
     22 )
     23 print("--- _output_TDC took %s seconds ---" % (time.time() - start_time))
     24 print(f'Tridesclous found {len(sorting_TDC.get_unit_ids())} units')

File ~\Anaconda3\envs\sienv\lib\site-packages\spikeinterface\sorters\runsorter.py:131, in run_sorter(sorter_name, recording, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, with_output, **sorter_params)
    129         else:
    130             container_image = singularity_image
--> 131     return run_sorter_container(
    132         container_image=container_image,
    133         mode=mode,
    134         **common_kwargs,
    135     )
    137 return run_sorter_local(**common_kwargs)

File ~\Anaconda3\envs\sienv\lib\site-packages\spikeinterface\sorters\runsorter.py:561, in run_sorter_container(sorter_name, recording, mode, container_image, output_folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, extra_requirements, **sorter_params)
    559 if run_error:
    560     if raise_error:
--> 561         raise SpikeSortingError(
    562             f"Spike sorting in {mode} failed with the following error:\n{run_sorter_output}")
    563 else:
    564     if with_output:

SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/Users/huynh/spike_epsztein/proj_louis/in_container_sorter_script.py", line 9, in <module>\n    recording = load_extractor(\'/Users/huynh/spike_epsztein/proj_louis/in_container_recording.json\')\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 883, in load_extractor\n    return BaseExtractor.load(file_or_folder_or_dict, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 522, in load\n    extractor = BaseExtractor.from_dict(d, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 349, in from_dict\n    extractor = _load_extractor_from_dict(d)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 826, in _load_extractor_from_dict\n    extractor = cls(**kwargs)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/binaryfolder.py", line 32, in __init__\n    with open(folder_path / \'binary.json\', \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'_preprocessed/binary.json\'\n'
```

**Comment by phanhuynh** [comment]
It happens with these dockers;  Tridesclous Spykingcircus IronClust Kilosort3

**Comment by phanhuynh** [comment]
Hi @alejoe91 , I image you must be very busy -- let me know if there's anything else I can provide.

**Comment by alejoe91** [comment]
Hi @phanhuynh so in this case the sorters seem to be just failing on that recording. Doesn't happen on all recordings?

**Comment by phanhuynh** [comment]
Hi @alejoe91 , I tried 4 dockerized sorters on two other data sets, so 8 attempts in total.  
For the first data set (neuropixel), it worked once (trideslous) and failed the remaining 3 times (Spykingcircus, IronClust, and Kilosort3).
For the second set (neuronexus 64 channels), it failed all 4 times.

There were two types of error messages.  The first one appeared 6 times, and the second occured once with the second data set + tridesclou.s
I noticed that in the first message, it mentions Spykingcircus2Sorter even if I used another sorter.  
For the second mesage, I've attached the binary.json file from the preprocessed folder . 
[binary.txt](https://github.com/SpikeInterface/spikeinterface/files/9029934/binary.txt)

FIRST ERROR MESSAGE:
```
SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/Users/huynh/spike_epsztein/proj_louis_2/in_container_sorter_script.py", line 4, in <module>\n    from spikeinterface.sorters import run_sorter_local\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/__init__.py", line 2, in <module>\n    from .sorterlist import *\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/sorterlist.py", line 19, in <module>\n    from .spyking_circus2 import Spykingcircus2Sorter\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/spyking_circus2/__init__.py", line 1, in <module>\n    from .spyking_circus2 import Spykingcircus2Sorter\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sorters/spyking_circus2/spyking_circus2.py", line 5, in <module>\n    from spikeinterface.sortingcomponents.clustering import find_cluster_from_peaks\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sortingcomponents/clustering/__init__.py", line 1, in <module>\n    from .method_list import clustering_methods\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sortingcomponents/clustering/method_list.py", line 4, in <module>\n    from .sliding_nn import SlidingNNClustering\n  File "/usr/local/lib/python3.8/dist-packages/spikeinterface/sortingcomponents/clustering/sliding_nn.py", line 19, in <module>\n    import hdbscan\nModuleNotFoundError: No module named \'hdbscan\'\n'

```

SECOND ERROR MESSAGE:
```
SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/Users/huynh/spike_epsztein/proj_neuronexus/in_container_sorter_script.py", line 9, in <module>\n    recording = load_extractor(\'/Users/huynh/spike_epsztein/proj_neuronexus/in_container_recording.json\')\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 883, in load_extractor\n    return BaseExtractor.load(file_or_folder_or_dict, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 522, in load\n    extractor = BaseExtractor.from_dict(d, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 349, in from_dict\n    extractor = _load_extractor_from_dict(d)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 826, in _load_extractor_from_dict\n    extractor = cls(**kwargs)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/binaryfolder.py", line 32, in __init__\n    with open(folder_path / \'binary.json\', \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'_preprocessed/binary.json\'\n'
```

**Comment by phanhuynh** [comment]
Hi @alejoe91 , fantastic!  Thank you!
The good news: for the Neuropixel data set, I successfully executed Tridesclous, and now I'm trying the other 3 sorters.
Bad news: for the Neuronexus dataset, I'm getting the second error message for all 4 sorters.

**Comment by phanhuynh** [comment]
Hi @alejoe91 , do you have a rough idea of the timeline for solving this?  Thank you so much :)

**Comment by alejoe91** [comment]
Hi @phanhuynh 

Can you try to name the folder without a space? like `_preprocessed_folder`. Maybe that extra space is causing issues...

**Comment by phanhuynh** [comment]
I tried "_preprocessed_folder" but it's the same error: 
(Also, I'm don't fully understand what you mean when you said "_prepocessed" has a space?)  

```
SpikeSortingError: Spike sorting in docker failed with the following error:
b'Traceback (most recent call last):\n  File "/Users/huynh/spike_epsztein/proj_louis/in_container_sorter_script.py", line 9, in <module>\n    recording = load_extractor(\'/Users/huynh/spike_epsztein/proj_louis/in_container_recording.json\')\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 883, in load_extractor\n    return BaseExtractor.load(file_or_folder_or_dict, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 522, in load\n    extractor = BaseExtractor.from_dict(d, base_folder=base_folder)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 349, in from_dict\n    extractor = _load_extractor_from_dict(d)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/base.py", line 826, in _load_extractor_from_dict\n    extractor = cls(**kwargs)\n  File "/usr/local/lib/python3.8/site-packages/spikeinterface/core/binaryfolder.py", line 32, in __init__\n    with open(folder_path / \'binary.json\', \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'_preprocessed_folder/binary.json\'\n'
```

**Comment by alejoe91** [comment]
Can you paste the content of the `_preprocessed` folder? Do you have a `binary.json` there?

**Comment by phanhuynh** [comment]
Yes, the binary.json file is there.  Here's the whole _prepocessed folder :  https://drive.google.com/file/d/1mLR8-nhmAgWD_E18Rze2Rsk8vhtyMTK-/view?usp=sharing

**Comment by alejoe91** [comment]
@samuelgarcia any idea?

**Comment by phanhuynh** [comment]
Hello @samuelgarcia and @alejoe91 , I hope you enjoyed some good rest last week!
I'm curious if you have any new ideas on this issue :)  Thank you!

**Comment by phanhuynh** [comment]
I'm starting to worry that this error is related to changes made to the dockers (just a guess) -- which would mean I'd have to install each of these sorters locally.  I really hope that's not true.  
Can you shed any light on this issue?

**Comment by alejoe91** [comment]
@phanhuynh maybe it would be easier if we chatted over zoom and tried a debug session. Can you send me an email so we can schedule?

**Comment by phanhuynh** [comment]
Yes!  That would be great :) phan@bu.edu.  I'm free any time today and tomorrow.
